config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comment
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  # validation
  	
end

app/models/timw.rb
class Timw < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    puts "hello there"
    @articles = Article.all
    #json_response(@articles,:created)
  end
 
  def show
    @article = Article.find(params[:id])
    
    @comments= Comment.all.where('article_id': params[:id])
    
     #json_response(@article,:created)

  end
 
  def new
    
  end
  def edit
    @article = Article.find(params[:id])
     json_response(@article,:created)
  end
 
  def create
    @article = Article.new(article_params)

    if @article.save
      json_response(@article)
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
    def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
	def index
		@article = Article.find(params[:article_id])
		@comments=@article.comment.all;
		json_response(@comments, @article,:created)
	end
	
    def new
		@article=Article.new
	end

	def create
		puts params
		@article = Article.find(params[:article_id])
        @comments = @article.comment.create(commenter: params[:commenter],body: params[:body])
        @comments.save
        #json_response(@comments,:created)
        #redirect_to article_comment_path(@comments) 
        redirect_to article_comment_url(id: @comments.id)
        
    end
    def show 
        @article = Article.find(params[:article_id])
        @comments = @article.comment.find(params[:id])
        json_response(@article,@comments,:created)
    end

    private  def comment_params
    	 params.require(:comment).permit(:commenter,:body)
    end
    def json_response(object,object2, status = :ok)
    
    render :json => {
     :o1 => object.as_json,
     :o2 => object2.as_json
   }
  end
end

app/controllers/del_id_controller.rb
class DelIdController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/del_id_helper.rb
module DelIdHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= form_for(@article) do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
    border: 2px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 15px;
}
</style>
</head>
<body>
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>

<table style="width:50%" >
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</body>
</html>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
 
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
    
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<% @comments.each do |comment| %>
    <p>
      <%= comment.id %><br>
      <%= comment.commenter %><br>
      <%= comment.body %> <br>
      <%=  comment.created_at %> <br>
      <%= comment.updated_at %> 

    </p>
  <% end %>
<%= form_for([@article, @article.comment.build]) do |f| %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :commenter %>
  </p>
 
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :body %>
  </p>
   
    <%= f.submit %>
  </p>
 
<% end %>

app/views/comments/create.html.erb
</p> <%= puts "manish" %> </p>

app/views/comments/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
    border: 2px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 15px;
}
</style>
</head>
<body>
<h1>Listing comments</h1>
<table style="width:50%" >
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 

  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.id %></td>
      <td><%= comment.commenter %></td>
      <td><%= comment.article_id %></td> 
      <td><%=  comment.created_at %></td> 
      <td><%= comment.updated_at %></td> 

    </tr>
  <% end %>
</table>
</body>
<%= link_to 'new', new_article_comment_path %>
</html>

app/views/comments/new.html.erb
<%= form_for :comment, url: article_comments_path do |f| %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :commenter %>
  </p>
 
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :body %>
  </p>
   
    <%= f.submit %>
  </p>
 
<% end %>

app/views/comments/show.html.erb
<p> ohk</p>

app/views/del_id/index.html.erb
<%= form_for :article, url: articles_path do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :id_no %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>